# -*- coding: utf-8 -*-
"""Telco_Churn_Correct_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ERvqmOUsb_BEIx_ucXavtWcvl3lzaPPP

# Telco Customer Churn — Correct ML Pipeline

This version keeps the final test set untouched until the last evaluation, places all preprocessing inside a scikit-learn pipeline, selects the model using cross-validation on training data only, and saves preprocessing together with the trained model.
"""

import os
import random
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.base import clone
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import HistGradientBoostingClassifier, RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, average_precision_score, classification_report,
    confusion_matrix, f1_score, precision_recall_curve, precision_score,
    recall_score, roc_auc_score, roc_curve
)
from sklearn.model_selection import (
    StratifiedKFold, cross_validate, cross_val_predict, train_test_split
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
sns.set_theme(style="whitegrid")

"""## 1. Upload and load the CSV

Upload `WA_Fn-UseC_-Telco-Customer-Churn.csv` when Colab asks for it.
"""

DATASET_NAME = "/content/WA_Fn-UseC_-Telco-Customer-Churn.csv"
candidate_paths = [Path(DATASET_NAME), Path("/content") / DATASET_NAME]
csv_path = next((p for p in candidate_paths if p.exists()), None)

if csv_path is None:
    try:
        from google.colab import files
        uploaded = files.upload()
        if not uploaded:
            raise FileNotFoundError("No CSV file was uploaded.")
        csv_path = Path(next(iter(uploaded.keys())))
    except ImportError as exc:
        raise FileNotFoundError(
            f"Put {DATASET_NAME} in the same folder as this notebook."
        ) from exc

df = pd.read_csv(csv_path)
print(f"Loaded: {csv_path}")
print(f"Shape: {df.shape}")
df.head()

"""## 2. Validate and clean the data

`TotalCharges` contains 11 blank strings. They belong to new customers with zero tenure, so they are converted to zero. Customer IDs are retained separately and never used as model features.
"""

required_columns = {
    "customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"
}
missing_columns = required_columns - set(df.columns)
if missing_columns:
    raise ValueError(f"Missing required columns: {sorted(missing_columns)}")

data = df.copy()
data["TotalCharges"] = pd.to_numeric(data["TotalCharges"], errors="coerce")

invalid_total = data["TotalCharges"].isna() & data["tenure"].ne(0)
if invalid_total.any():
    median_total = data.loc[~invalid_total, "TotalCharges"].median()
    data.loc[invalid_total, "TotalCharges"] = median_total
data.loc[data["TotalCharges"].isna() & data["tenure"].eq(0), "TotalCharges"] = 0.0

if not data["Churn"].isin(["Yes", "No"]).all():
    raise ValueError("Churn must contain only 'Yes' and 'No'.")

customer_ids = data.pop("customerID")
data["Churn"] = data["Churn"].map({"No": 0, "Yes": 1}).astype("int8")

print("Missing values:", int(data.isna().sum().sum()))
print("Class distribution:")
display(data["Churn"].value_counts(normalize=True).rename("ratio").to_frame())

"""## 3. Create the untouched final test set

The test set is not used for preprocessing, model selection, cross-validation, or threshold selection.
"""

X = data.drop(columns="Churn")
y = data["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=SEED,
    stratify=y
)

numeric_features = ["tenure", "MonthlyCharges", "TotalCharges"]
categorical_features = [c for c in X.columns if c not in numeric_features]

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

try:
    one_hot = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
except TypeError:  # Compatibility with older scikit-learn versions
    one_hot = OneHotEncoder(handle_unknown="ignore", sparse=False)

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", one_hot)
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

print("Train:", X_train.shape, "Test:", X_test.shape)

"""## 4. Compare models using training data only

ROC-AUC is the selection metric. PR-AUC, recall, precision, and F1 are also reported because churn is imbalanced.
"""

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=3000, random_state=SEED
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=500, min_samples_leaf=3,
        class_weight="balanced_subsample", random_state=SEED, n_jobs=1
    ),
    "Histogram Gradient Boosting": HistGradientBoostingClassifier(
        max_iter=300, learning_rate=0.05,
        l2_regularization=1.0, random_state=SEED
    )
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
scoring = {
    "roc_auc": "roc_auc",
    "pr_auc": "average_precision",
    "precision": "precision",
    "recall": "recall",
    "f1": "f1"
}

cv_rows = []
pipelines = {}

for name, estimator in models.items():
    pipeline = Pipeline([
        ("preprocess", clone(preprocessor)),
        ("model", estimator)
    ])
    pipelines[name] = pipeline
    scores = cross_validate(
        pipeline, X_train, y_train,
        cv=cv, scoring=scoring, n_jobs=-1
    )
    cv_rows.append({
        "model": name,
        **{metric: scores[f"test_{metric}"].mean() for metric in scoring},
        "roc_auc_std": scores["test_roc_auc"].std()
    })

cv_results = (
    pd.DataFrame(cv_rows)
    .sort_values("roc_auc", ascending=False)
    .reset_index(drop=True)
)
display(cv_results.round(4))

best_model_name = cv_results.loc[0, "model"]
best_pipeline = pipelines[best_model_name]
print("Selected model:", best_model_name)

"""## 5. Select the decision threshold using out-of-fold training predictions

The threshold maximizes F1 on training out-of-fold predictions. Change this rule if the business values recall or precision differently.
"""

oof_probabilities = cross_val_predict(
    best_pipeline,
    X_train,
    y_train,
    cv=cv,
    method="predict_proba",
    n_jobs=-1
)[:, 1]

precision_curve, recall_curve, thresholds = precision_recall_curve(
    y_train, oof_probabilities
)
f1_curve = (
    2 * precision_curve[:-1] * recall_curve[:-1]
    / np.maximum(precision_curve[:-1] + recall_curve[:-1], 1e-12)
)
best_threshold = float(thresholds[np.argmax(f1_curve)])
print(f"Selected threshold: {best_threshold:.4f}")
print(f"Training OOF F1 at selected threshold: {np.max(f1_curve):.4f}")

"""## 6. Fit once and evaluate the final test set once"""

final_model = clone(best_pipeline)
final_model.fit(X_train, y_train)

test_probabilities = final_model.predict_proba(X_test)[:, 1]
test_predictions = (test_probabilities >= best_threshold).astype(int)

final_metrics = pd.Series({
    "ROC-AUC": roc_auc_score(y_test, test_probabilities),
    "PR-AUC": average_precision_score(y_test, test_probabilities),
    "Accuracy": accuracy_score(y_test, test_predictions),
    "Precision": precision_score(y_test, test_predictions, zero_division=0),
    "Recall": recall_score(y_test, test_predictions, zero_division=0),
    "F1": f1_score(y_test, test_predictions, zero_division=0)
}, name="Final test score")

display(final_metrics.round(4).to_frame())
print("\nClassification report:\n")
print(classification_report(
    y_test, test_predictions,
    target_names=["No Churn", "Churn"], zero_division=0
))

cm = confusion_matrix(y_test, test_predictions)
fpr, tpr, _ = roc_curve(y_test, test_probabilities)
test_precision_curve, test_recall_curve, _ = precision_recall_curve(
    y_test, test_probabilities
)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

sns.heatmap(
    cm, annot=True, fmt="d", cmap="Blues", cbar=False, ax=axes[0],
    xticklabels=["No Churn", "Churn"],
    yticklabels=["No Churn", "Churn"]
)
axes[0].set_title("Confusion Matrix")
axes[0].set_xlabel("Predicted")
axes[0].set_ylabel("Actual")

axes[1].plot(fpr, tpr, label=f"AUC = {final_metrics['ROC-AUC']:.3f}")
axes[1].plot([0, 1], [0, 1], "--", color="gray")
axes[1].set_title("ROC Curve")
axes[1].set_xlabel("False Positive Rate")
axes[1].set_ylabel("True Positive Rate")
axes[1].legend()

axes[2].plot(
    test_recall_curve, test_precision_curve,
    label=f"PR-AUC = {final_metrics['PR-AUC']:.3f}"
)
axes[2].set_title("Precision–Recall Curve")
axes[2].set_xlabel("Recall")
axes[2].set_ylabel("Precision")
axes[2].legend()

plt.tight_layout()
plt.show()

"""## 7. Save the complete inference artifact

The saved file contains the fitted preprocessing pipeline, model, threshold, expected feature columns, and model name.
"""

artifact = {
    "pipeline": final_model,
    "threshold": best_threshold,
    "feature_columns": X.columns.tolist(),
    "model_name": best_model_name
}

MODEL_FILE = "telco_churn_pipeline.joblib"
joblib.dump(artifact, MODEL_FILE)
print(f"Saved: {MODEL_FILE}")

# Test loading and inference on one row
loaded_artifact = joblib.load(MODEL_FILE)
example_probability = loaded_artifact["pipeline"].predict_proba(
    X_test.iloc[[0]]
)[0, 1]
example_prediction = int(example_probability >= loaded_artifact["threshold"])
print({
    "churn_probability": round(float(example_probability), 4),
    "churn_prediction": example_prediction
})

# Uncomment in Google Colab to download the trained artifact:
# from google.colab import files
# files.download(MODEL_FILE)